print("hh       hh   eeeeeeeeee  l                   l                oooooooooooooo      W          ")
print("hh       hh   eeeeeeee    ll                 ll                oo          oo      O ")
print("hh       hh   ee          lll               lll                oo          oo      R")
print("hh       hh   ee          lll               lll                oo          oo      L") 
print("hh       hh   ee          lll               lll                oo          oo      D")
print("hhhhhhhhhhh   eeeeeee     lll               lll                oo          oo      :)
print("hh       hh   eeeeeee     lllllllllllllll   llllllllllllll      ooooooooooooo                                       ")
print("hh       hh   eeeeeeeee   lllllllllllll     llllllllllll                                              ")
